# Generated by Django 3.2 on 2021-04-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='auth_emp1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emp1', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='auth_emp2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emp2', to='api.employee'),
        ),
    ]
