# Generated by Django 3.2 on 2021-04-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210420_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absenserecord',
            options={'verbose_name': 'AbsenseRecord', 'verbose_name_plural': 'AbsenseRecords'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
    ]
